# Generated by Django 4.0.4 on 2022-07-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='answer',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cards',
            name='question',
            field=models.CharField(max_length=300),
        ),
    ]
